### ISSUE TITLE
np.rad2deg

### ISSUE THREAD

**Issue by CJ-Wright** [python-quantities/python-quantities#139]
```python
Traceback (most recent call last):
  File "/home/christopher/mc/envs/hw/lib/python3.5/site-packages/quantities/quantity.py", line 231, in __array_prepare__
    res._dimensionality = p_dict[uf](*objs)
KeyError: <ufunc 'rad2deg'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/christopher/DATA/academics/xray/ps4/problem1.py", line 19, in <module>
    print(np.rad2deg(theta))
  File "/home/christopher/mc/envs/hw/lib/python3.5/site-packages/quantities/quantity.py", line 236, in __array_prepare__
    """ % uf
ValueError: ufunc <ufunc 'rad2deg'> not supported by quantities
                please file a bug report at https://github.com/python-quantities
```

**Comment by thisch** [comment]
@CJ-Wright Why do you want to pass a quantity to `rad2deg` instead of using `.rescale` ?

**Comment by CJ-Wright** [comment]
Fair point, although I think it would be good to handle this case if possible, since functions that quantities are being passed to may not be aware that the data being passed in is a quantity and so use `rad2deg`.
