### ISSUE TITLE
ufunc %r not supported by quantities

### ISSUE THREAD

**Issue by dkogan** [python-quantities/python-quantities#145]
Hi. On the latest debian/unstable I run a python2 program that contains just "import quantities", and this fails:

```
dima@fatty:/tmp$ cat /tmp/tst.py
import quantities

dima@fatty:/tmp$ python2 /tmp/tst.py
Traceback (most recent call last):
  File "/tmp/tst.py", line 1, in <module>
    import quantities
  File "/usr/lib/python2.7/dist-packages/quantities/__init__.py", line 283, in <module>
    from .units import *
  File "/usr/lib/python2.7/dist-packages/quantities/units/__init__.py", line 9, in <module>
    from . import acceleration
  File "/usr/lib/python2.7/dist-packages/quantities/units/acceleration.py", line 7, in <module>
    from .time import s
  File "/usr/lib/python2.7/dist-packages/quantities/units/time.py", line 18, in <module>
    aliases=['milliseconds']
  File "/usr/lib/python2.7/dist-packages/quantities/unitquantity.py", line 62, in __new__
    ret._conv_ref = definition._reference
  File "/usr/lib/python2.7/dist-packages/quantities/quantity.py", line 139, in _reference
    rq = rq * u._reference**d
  File "/usr/lib/python2.7/dist-packages/quantities/unitquantity.py", line 230, in __pow__
    return self.view(Quantity).__pow__(other)
  File "/usr/lib/python2.7/dist-packages/quantities/quantity.py", line 88, in g
    return f(self, other, *args)
  File "/usr/lib/python2.7/dist-packages/quantities/quantity.py", line 321, in __pow__
    return super(Quantity, self).__pow__(other)
  File "/usr/lib/python2.7/dist-packages/quantities/quantity.py", line 236, in __array_prepare__
    """
ValueError: ufunc %r not supported by quantities
                please file a bug report at https://github.com/python-quantities
                

dima@fatty:/tmp$ dpkg -l python-quantities
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version          Architecture     Description
+++-=======================-================-================-===================================================
ii  python-quantities       0.10.1-1         all              Library for computation of physical quantities with
```

0.10.1-1 is the latest in Debian currently. I haven't tried the latest release yes. Is this a known issue with 0.10?

**Comment by dkogan** [comment]
I took a deeper look, and apparently 0.10.1 is ancient. Just tested 0.12.0, and it does not have this problem. I will update the Debian package. Thanks.
