### ISSUE TITLE
Tests failing with Python3.7

### ISSUE THREAD

**Issue by sanjayankur31** [python-quantities/python-quantities#148]
Tests failed while the Fedora Python3.7 mass rebuild. They passed with Python3.6, so it must be a change between the versions. I'm still debugging it. Here's the offending test(s) if anyone else has any ideas:

```
+ /usr/bin/python2 setup.py test
running test
.....................................x........u.x.....................x.....................................................................................
----------------------------------------------------------------------
Ran 156 tests in 0.808s
OK (expected failures=3, unexpected successes=1)
+ /usr/bin/python3 setup.py test
running test
............................E...............................................................................x........u.x.....................x..............
======================================================================
ERROR: test_dimensionality_str (quantities.tests.test_dimensionality.TestDimensionality)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.7/sre_parse.py", line 1021, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\c'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builddir/build/BUILD/quantities-0.12.1/quantities/tests/test_dimensionality.py", line 27, in test_dimensionality_str
    self.assertEqual(joule.latex, joule_tex)
  File "/builddir/build/BUILD/quantities-0.12.1/quantities/dimensionality.py", line 53, in latex
    return markup.format_units_latex(self)
  File "/builddir/build/BUILD/quantities-0.12.1/quantities/markup.py", line 126, in format_units_latex
    res = re.sub(r'\*','{'+mult+'}',res)
  File "/usr/lib64/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib64/python3.7/re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib64/python3.7/re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib64/python3.7/sre_parse.py", line 1024, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \c at position 1
----------------------------------------------------------------------
Ran 156 tests in 0.831s
```

The complete build log is [here](https://kojipkgs.fedoraproject.org//work/tasks/3561/27753561/build.log)

I reckon it is related to [this particular change](https://docs.python.org/3.7/whatsnew/3.7.html#api-and-feature-removals): `Unknown escapes consisting of '\' and an ASCII letter in replacement templates for re.sub() were deprecated in Python 3.5, and will now cause an error.`

**Comment by bjodah** [comment]
Just ran into this as well:
```
$ python3.7 -c "import quantities as pq; print(pq.second.dimensionality.latex)"
...
re.error: bad escape \c at position 1
```

**Comment by Shubham-Goyal123** [comment]
I write a code in pycharm from windows 10 for getting the data of whois
like# **import pythonwhois**
i am getting error
 File "C:\python37\lib\sre_parse.py", line 1021, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\s'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>

please help me
