### ISSUE TITLE
ERROR: test_clip (quantities.tests.test_methods.TestQuantityMethods): ValueError: ufunc <ufunc 'clip'> not supported by quantities

### ISSUE THREAD

**Issue by sanjayankur31** [python-quantities/python-quantities#158]
A test is failing in our builds now:

```
======================================================================
ERROR: test_clip (quantities.tests.test_methods.TestQuantityMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/quantities-0.12.2/quantities/quantity.py", line 247, in __array_prepare__
    res._dimensionality = p_dict[uf](*objs)
KeyError: <ufunc 'clip'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/quantities-0.12.2/quantities/tests/test_methods.py", line 198, in test_clip
    self.methodWithOut(
  File "/builddir/build/BUILD/quantities-0.12.2/quantities/tests/test_methods.py", line 125, in methodWithOut
    ret = getattr(q.copy(), name)(*args, out=out, **kw)
  File "/builddir/build/BUILD/quantities-0.12.2/quantities/quantity.py", line 579, in clip
    clipped = self.magnitude.clip(
  File "/usr/lib64/python3.8/site-packages/numpy/core/_methods.py", line 131, in _clip
    return _clip_dep_invoke_with_casting(
  File "/usr/lib64/python3.8/site-packages/numpy/core/_methods.py", line 85, in _clip_dep_invoke_with_casting
    return ufunc(*args, out=out, **kwargs)
  File "/builddir/build/BUILD/quantities-0.12.2/quantities/quantity.py", line 249, in __array_prepare__
    raise ValueError(
ValueError: ufunc <ufunc 'clip'> not supported by quantities
                please file a bug report at https://github.com/python-quantities
                

----------------------------------------------------------------------
Ran 161 tests in 1.156s
```

Versions of software:

- python-quantities 0.12.3 with these dependencies:

```
DEBUG util.py:587:  Dependencies resolved.
DEBUG util.py:587:  ================================================================================
DEBUG util.py:587:   Package                      Arch        Version              Repository  Size
DEBUG util.py:587:  ================================================================================
DEBUG util.py:587:  Installing:
DEBUG util.py:587:   python3-devel                x86_64      3.7.4-4.fc31         build      204 k
DEBUG util.py:587:   python3-numpy                x86_64      1:1.17.0-2.fc31      build      4.4 M
DEBUG util.py:587:   python3-setuptools           noarch      41.0.1-4.fc31        build      578 k
DEBUG util.py:587:  Installing dependencies:
DEBUG util.py:587:   gdbm-libs                    x86_64      1:1.18-5.fc31        build       55 k
DEBUG util.py:587:   libgfortran                  x86_64      9.1.1-2.fc31.1       build      723 k
DEBUG util.py:587:   libquadmath                  x86_64      9.1.1-2.fc31.1       build      200 k
DEBUG util.py:587:   openblas                     x86_64      0.3.6-3.fc31         build       29 k
DEBUG util.py:587:   openblas-threads             x86_64      0.3.6-3.fc31         build      4.5 M
DEBUG util.py:587:   python-pip-wheel             noarch      19.1.1-4.fc31        build      1.1 M
DEBUG util.py:587:   python-rpm-macros            noarch      3-47.fc31            build       13 k
DEBUG util.py:587:   python-setuptools-wheel      noarch      41.0.1-4.fc31        build      276 k
DEBUG util.py:587:   python3                      x86_64      3.7.4-4.fc31         build       34 k
DEBUG util.py:587:   python3-libs                 x86_64      3.7.4-4.fc31         build      7.3 M
DEBUG util.py:587:   python3-rpm-generators       noarch      9-2.fc31             build       23 k
DEBUG util.py:587:   python3-rpm-macros           noarch      3-47.fc31            build       11 k
DEBUG util.py:587:   sqlite-libs                  x86_64      3.29.0-2.fc31        build      568 k
DEBUG util.py:587:  Transaction Summary
DEBUG util.py:587:  ================================================================================
```

Logs:
- [build.txt](https://github.com/python-quantities/python-quantities/files/3466779/build.txt)
- [root.txt](https://github.com/python-quantities/python-quantities/files/3466780/root.txt)

NOTE: This test also fails with 0.12.2 and Python 3.8. Bug about that just filed here:
https://bugzilla.redhat.com/show_bug.cgi?id=1737361

**Comment by sanjayankur31** [comment]
Looks like this is related to numpy 1.17 which changes some stuff related to the clip ufunc:
https://github.com/numpy/numpy/blob/master/doc/release/1.17.0-notes.rst#clip-now-uses-a-ufunc-under-the-hood

I see that the CI here only tests till numpy 1.16 which is how this bug slipped through.

**Comment by bjodah** [comment]
Does this upcoming change to NumPy fix the tests?
https://github.com/numpy/numpy/pull/14194

**Comment by sanjayankur31** [comment]
> Does this upcoming change to NumPy fix the tests?
> [numpy/numpy#14194](https://github.com/numpy/numpy/pull/14194)

I don't currently have access to an environment where I can test that out, unfortunately. I'll have to wait for the release.

**Comment by thisch** [comment]
I've just applied the patch from numpy/numpy#14194 to my numpy v1.17 installation, but it does not fix the unit-test issue.

**Comment by thisch** [comment]
Unyt has the same issue: https://github.com/yt-project/unyt/issues/101

**Comment by thisch** [comment]
This small patch fixes the tests:

```'diff
diff --git a/quantities/dimensionality.py b/quantities/dimensionality.py
index b2ab0e5..fe6eae5 100644
--- a/quantities/dimensionality.py
+++ b/quantities/dimensionality.py
@@ -329,6 +329,11 @@ p_dict[np.floor] = _d_copy
 p_dict[np.fix] = _d_copy
 p_dict[np.ceil] = _d_copy
 
+def _d_clip(a1, a2, a3, q):
+    return q.dimensionality
+
+p_dict[np.core.umath.clip] = _d_clip
```

Feel free to open a PR with this fix.

**Comment by sanjayankur31** [comment]
It seems to work for numpy>=1.17.0 only. Would that be OK?

**Comment by sanjayankur31** [comment]
Could one of the devs please look at this and include the fix if it's OK? I don't know enough about the library myself.

**Comment by knedlsepp** [comment]
@apdavison would you mind taking a look?
