### ISSUE TITLE
TypeError: arctan2() takes from 2 to 3 positional arguments but 1 were given [numpy 1.21]

### ISSUE THREAD

**Issue by mgorny** [python-quantities/python-quantities#190]
It seems that there are regressions with numpy 1.21:

```pytb
$ python -m unittest
......./tmp/python-quantities-0.12.5/quantities/tests/test_arithmetic.py:57: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  self._typeDict = np.typeDict.copy()
.........................................................................................................E.....x........u.x......................x..............
======================================================================
ERROR: test_arctan2 (quantities.tests.test_umath.TestUmath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/python-quantities-0.12.5/quantities/tests/test_umath.py", line 229, in test_arctan2
    self.assertRaises(ValueError, np.arctan2, (1*pq.m, 1*pq.m))
  File "/usr/lib/python3.8/unittest/case.py", line 816, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.8/unittest/case.py", line 202, in handle
    callable_obj(*args, **kwargs)
TypeError: arctan2() takes from 2 to 3 positional arguments but 1 were given

----------------------------------------------------------------------
Ran 167 tests in 1.315s

FAILED (errors=1, expected failures=3, unexpected successes=1)
```

**Comment by mgorny** [comment]
Hmm, FWICS they've just changed `ValueError` to `TypeError`. I'll submit a PR shortly.
