### ISSUE TITLE
`numpy.core` is deprecated as of Numpy 2.0

### ISSUE THREAD

**Issue by domdfcoding** [python-quantities/python-quantities#234]
Accessing `numpy.core`, as quantities does in just one place, triggers a deprecation warning.

https://github.com/python-quantities/python-quantities/blob/b47419a6e41ec076da47909e6aea2f27189ff678/quantities/dimensionality.py#L330-L335

```python3
$ python3 -Werror -c "import quantities"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv/lib/python3.9/site-packages/quantities/__init__.py", line 273, in <module>
    from . import quantity
  File "/tmp/venv/lib/python3.9/site-packages/quantities/quantity.py", line 10, in <module>
    from .dimensionality import Dimensionality, p_dict
  File "/tmp/venv/lib/python3.9/site-packages/quantities/dimensionality.py", line 333, in <module>
    p_dict[np.core.umath.clip] = _d_clip
  File "/tmp/venv/lib/python3.9/site-packages/numpy/core/__init__.py", line 31, in __getattr__
    _raise_warning(attr_name)
  File "/tmp/venv/lib/python3.9/site-packages/numpy/core/_utils.py", line 10, in _raise_warning
    warnings.warn(
DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.umath.
```

The module still exists but has been made private as `numpy._core`. I have searched for a direct alternative to `umath.clip`  but can't find one listed.

**Comment by domdfcoding** [comment]
There are also a lot of deprecation warnings for `__array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)` throughout the codebase.



 <details>
  <summary>These are all triggered just from importing quantities:</summary>

```python3
$ PYTHONDEVMODE=1 python3 -c "import quantities"
/tmp/venv/lib/python3.9/site-packages/quantities/dimensionality.py:333: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.umath.
  p_dict[np.core.umath.clip] = _d_clip
/tmp/venv/lib/python3.9/site-packages/quantities/unitquantity.py:203: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  return self.view(Quantity).__mul__(other)
/tmp/venv/lib/python3.9/site-packages/quantities/quantity.py:341: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  return np.multiply(other, self)
/tmp/venv/lib/python3.9/site-packages/quantities/quantity.py:357: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  return np.power(self, other)
/tmp/venv/lib/python3.9/site-packages/quantities/quantity.py:138: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rq = rq * u._reference**d
/tmp/venv/lib/python3.9/site-packages/quantities/quantity.py:139: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  return rq * self.magnitude
/tmp/venv/lib/python3.9/site-packages/quantities/unitquantity.py:211: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  return self.view(Quantity).__truediv__(other)
/tmp/venv/lib/python3.9/site-packages/quantities/units/length.py:135: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  127*mm/360,
/tmp/venv/lib/python3.9/site-packages/quantities/units/length.py:148: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  1200*m/3937,
/tmp/venv/lib/python3.9/site-packages/quantities/quantity.py:351: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  return np.true_divide(other, self)
/tmp/venv/lib/python3.9/site-packages/quantities/units/acceleration.py:11: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  9.806650*m/s**2,
/tmp/venv/lib/python3.9/site-packages/quantities/units/force.py:13: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  kg*m/s**2,
/tmp/venv/lib/python3.9/site-packages/quantities/units/force.py:19: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  gram*cm/s**2,
/tmp/venv/lib/python3.9/site-packages/quantities/units/force.py:49: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  lb*ft/s**2,
/tmp/venv/lib/python3.9/site-packages/quantities/units/electromagnetism.py:51: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  1 * erg**0.5 * cm**0.5,
/tmp/venv/lib/python3.9/site-packages/quantities/units/electromagnetism.py:304: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  4*pi*10**-7*N/A**2,
/tmp/venv/lib/python3.9/site-packages/quantities/units/pressure.py:13: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  gravity*13.59510*g/cm**3
/tmp/venv/lib/python3.9/site-packages/quantities/units/pressure.py:15: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  mercury_60F = UnitQuantity('mercury_60F', gravity*13556.8*kg/m**3)
/tmp/venv/lib/python3.9/site-packages/quantities/units/pressure.py:16: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  H2O = h2o = water = conventional_water = UnitQuantity('H2O', gravity*1000*kg/m**3)
/tmp/venv/lib/python3.9/site-packages/quantities/units/pressure.py:17: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  water_4C = water_39F = UnitQuantity('water_4C', gravity*999.972*kg/m**3)
/tmp/venv/lib/python3.9/site-packages/quantities/units/pressure.py:18: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  water_60F = UnitQuantity('water_60F', gravity*999.001*kg/m**3)
/tmp/venv/lib/python3.9/site-packages/quantities/units/pressure.py:86: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  kg*gravity/cm**2,
/tmp/venv/lib/python3.9/site-packages/quantities/units/pressure.py:96: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  pound*gravity/inch**2,
/tmp/venv/lib/python3.9/site-packages/quantities/units/pressure.py:106: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  0.1*N/m**2,
<string>:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)

```

</details>

**Comment by zm711** [comment]
See #232 which is working to address this already.
